import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import OgImage from '../public/og_image.png';
import Slider from '../components/Slider'

import build1 from "../public/AugGetBuilding01.png";
import build2 from "../public/AugGetBuilding02.png";
import build3 from "../public/AugGetBuilding03.png";
import build4 from "../public/AugGetBuilding04.png";
import build5 from "../public/AugGetBuilding05.png";

// moves slider images
import move1 from "../public/AugMoves01.png";
import move2 from "../public/AugMoves02.png";
import move3 from "../public/AugMoves03.png";
import move4 from "../public/AugMoves04.png";
import move5 from "../public/AugMoves05.png";
// Juno slider images
import juno1 from "../public/AugJuno01.png";
import juno2 from "../public/AugJuno02.png";
import juno3 from "../public/AugJuno03.png";
import juno4 from "../public/AugJuno04.png";
import juno5 from "../public/AugJuno05.png";
// StonerCats slider images
import StonerCats1 from "../public/AugStonerCats01.png";
import StonerCats2 from "../public/AugStonerCats02.png";
import StonerCats3 from "../public/AugStonerCats03.png";
import StonerCats4 from "../public/AugStonerCats04.png";
import StonerCats5 from "../public/AugStonerCats05.png";

const inter = Inter({ subsets: ['latin'] })

function Home({host}: {host: string}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Slider images={[move1, move2, move3, move4, move5]} />
        <Slider images={[juno1, juno2, juno3, juno4, juno5]} />
        <Slider images={[build1, build2, build3, build4, build5]} />
        <Slider images={[StonerCats1, StonerCats2, StonerCats3, StonerCats4, StonerCats5]} />
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}

Home.getInitialProps = async (ctx: any) => {
  const { req, query, res, asPath, pathname } = ctx;
  let host;
  if (req) {
    host = req.headers.host
  }
  return { host: String(host) }
}

export default Home